### PR TITLE
Adds function addPostDataRaw

### PR DESCRIPTION
**Pull request by Bownairo**
Implements the function addPostDataRaw for putting raw data into to body of a post request.

### CODE REVIEW

**Comment by Lectem** [comment]
Please edit your commit so that there are no linespace changes (use git commit --amend and git push -f)

**Comment by yellows8** [comment]
This is missing a httpc* wrapper func which the other context-specific code use as well.

**Comment by Bownairo** [comment]
Did you ever make a similar change when implementing addPostDataAscii?

**Comment by yellows8** [comment]
"Did you ever make a similar change when implementing addPostDataAscii?" https://github.com/smealum/ctrulib/blob/b0c5a3c87d570508e96fb1e6718b8e55c678a720/libctru/source/services/httpc.c#L124

**Comment by Bownairo** [comment]
I'm pretty positive I already have that implemented, are you sure I'm missing something?

**Comment by yellows8** [comment]
Those comments in the .h are still wrong, please base it on 3dbrew. You should not be handling "Raw" data as a string either.

**Comment by Bownairo** [comment]
I redid the params to pass the data as a u32 pointer directly instead of a string. Where are my comments still wrong?

**Comment by profi200** [comment]
For unknown RAW data void* is good.

**Comment by Bownairo** [comment]
From the looks of it, everything gets passed to cmdbuff as a u32 anyway, but it's not a hard fix to use a void pointer instead, if that's a more appropriate solution.

**Comment by yellows8** [comment]
"Where are my comments still wrong?" NVM, thought this was another command which was actually documented on 3dbrew. Please document it on 3dbrew.

**Comment by yellows8** [comment]
These "Lenght" typos need fixed.

**Comment by Bownairo** [comment]
Typo has been fixed and wiki has been updated.

**Comment by yellows8** [comment]
The .h comments don't really match what you added to the wiki, the former should be updated("form field").

**Comment by Bownairo** [comment]
I changed "body" to "form field." What can I change next?

**Comment by yellows8** [comment]
I'm not sure what "form" is supposed to mean here when there's no name-buffer used with that command.

**Comment by Bownairo** [comment]
I changed everything back to POST body.

**Pull request merged**
