### PR TITLE
Rewrite most documentation to be consistent in format.

### PR DESCRIPTION
**Pull request by Steveice10**
This PR rewrites most of the ctrulib documentation to be consistent with the established doxygen format. It is targeted towards the great-refactor branch.

Let me know if there are any issues with the rewritten documentation.

### CODE REVIEW

**Comment by Lectem** [comment]
Could you add 
```c
/**
 * @file nameofthefile
 * @brief short descritpion
 */
```
In the files you documented ?
This is required so that it will be shown in the doxygen documentation

**Comment by fincs** [comment]
This looks pretty good.

**Comment by Lectem** [comment]
LGTM once the ```@file``` is added

**Comment by Steveice10** [comment]
Added file information.

**Pull request merged**
