### PR TITLE
add SVC 0x61, 0x62, 0x63, 0x64

### PR DESCRIPTION
**Pull request by patois**

### CODE REVIEW

**Comment by fincs** [comment]
Looks better now. I'd change `tid` to `thread_id`, and `u32 eventdata[6]` by an union containing all the event info structures. ExitThreadEvent, ExitProcessEvent [are documented](http://3dbrew.org/wiki/SVC#EXIT_THREAD.2FPROCESS_events), only a single u32 reason field is used (enums for which are missing in the patch).

**Comment by patois** [comment]
thanks. on it.

**Comment by patois** [comment]
Done. Thanks for your review!
DLL_LOAD and DLL_UNLOAD are not documented on 3dbrew, or did I miss those somewhere?
How are recent changes to be merged? Am I supposed to file a new pull request (first time for me :-) )?

**Comment by fincs** [comment]
Finally, the union that you create should be anonymous (that is, remove the `u`).

It is customary for the author of the pull request to squash their multiple commits into a single one before submitting the pull request. In this case, it suffices for you to force-push to your branch after performing the squash -- GitHub will automatically remove the old unsquashed commits and replace them by your new squashed commit.

**Comment by patois** [comment]
Thanks a lot for being really helpful!

**Pull request merged**
