### PR TITLE
Added missing am service cmds and changed the names to reflect 3dbrews d...

### PR DESCRIPTION
**Pull request by profi200**
...ocs.

All added functions are tested.

### CODE REVIEW

**Comment by WinterMute** [comment]
Please don't mix whitespace changes with code changes.

I'm not convinced by the function name changes either but diffs get really hard to read if you both rename a function and move it's position so far.

**Comment by profi200** [comment]
https://github.com/profi200/ctrulib/blob/master/libctru/include/3ds/services/am.h#L51-58
https://github.com/profi200/ctrulib/blob/master/libctru/include/3ds/services/am.h#L61-69

https://github.com/profi200/ctrulib/blob/master/libctru/source/services/am.c#L68-83
https://github.com/profi200/ctrulib/blob/master/libctru/source/services/am.c#L85-101

The other things are just position/name changes. I think it's better to use the 3dbrew names.

**Comment by WinterMute** [comment]
3dbrew can change to reflect libcrtu naming, there's no particular reason for slavishly sticking to what it currently says on 3dbrew. Especially if that means a function gets called AM_StartInstallCIADB1 rather than AM_StartDlpChildCiaInstall

**Comment by profi200** [comment]
The description in the header file clearly says what it does.
And that's actually what it does. It installs the title in DB 1.

**Comment by yellows8** [comment]
"It installs the title in DB 1" Which is the same as "DlpChild", aka the tmp DB.

**Pull request closed without merging**
