### PR TITLE
Added RTC example

### PR DESCRIPTION
**Pull request by Aurelio92**
This example shows how to get os time and prints it on top screen

### CODE REVIEW

**Comment by linoma** [comment]
is it ready? :dancers:

**Comment by Aurelio92** [comment]
No. Meanwhile you can use the osGetTime function just as it is shown in this example

**Comment by WinterMute** [comment]
time now works. Sorry to take so long - it was dependent on some things in devkitARM r44.

Could you update for latest libctru - accounting for already initialised services etc. Also use $(MAKE) in the makefiles rather than using make directly. That allows things to work on BSD where gnu make is known as gmake & also passes on -j parameters.

**Comment by linoma** [comment]
ooohhh yeah ;)

**Comment by smealum** [comment]
so does that mean we can close this now ?

**Comment by archshift** [comment]
Note that this won't even build with the latest libctru.

**Comment by Aurelio92** [comment]
Damn I still have to update this example... I'll do it right now

**Comment by smealum** [comment]
lgtm

**Pull request merged**
