### PR TITLE
svc.h: Remove volatile for getThreadLocalStorage

### PR DESCRIPTION
**Pull request by 173210**
Refer to comments in pull request #117.

### CODE REVIEW

**Comment by smealum** [comment]
didn't @WinterMute's comment on #110 say we should use __asm__ ?

**Comment by 173210** [comment]
I'll fix with another commit. Please merge this at first.

**Comment by smealum** [comment]
i think you can just add another commit to this same PR

**Comment by 173210** [comment]
That's right. But I don't have time to add commits now. I'll add other commits when I'm free.

**Comment by smealum** [comment]
i'll just merge and make an inline commit, thanks

**Comment by 173210** [comment]
Thank you.

**Comment by smealum** [comment]
done, should be fine now.

**Pull request merged**
