### PR TITLE
svc.h: Improve compatiblity

### PR DESCRIPTION
**Pull request by 173210**
Refer WinterMute's comment in this pull request.
https://github.com/smealum/ctrulib/pull/110

### CODE REVIEW

**Comment by WinterMute** [comment]
you don't need to use \__volatile__, the volatile keyword exists with -ansi, -pedantic & all the -std options I've tried.

**Comment by 173210** [comment]
I used __volatile__ because other header files use it.

**Comment by yuriks** [comment]
I don't think this particular asm snippet even need the volatile keyword: it has no side effects apart from the output register. This means that omitting the volatile is safe.

**Comment by 173210** [comment]
That's right, I'll open another pull request.

**Comment by 173210** [comment]
Please merge #123.

**Pull request closed without merging**
