### PR TITLE
HTTPC_AddRequestHeaderField Fix

### PR DESCRIPTION
**Pull request by LunarCookies**

### CODE REVIEW

**Comment by WinterMute** [comment]
why 12?

**Comment by LunarCookies** [comment]
It's L2, the strlen + 1 of the value parameter as documented here: http://3dbrew.org/wiki/HTTPC:AddRequestHeader

**Comment by WinterMute** [comment]
why is the length of the value parameter 12?

**Comment by LunarCookies** [comment]
It's not a number, it's a variable name: L2 (in lowercase)

**Comment by WinterMute** [comment]
can you change those variables to some sensible name while you're there, please?

**Comment by mtheall** [comment]
I vote name_len and value_len.

**Comment by LunarCookies** [comment]
Those was the names provided by the original developer I suppose it's not by to me to change them

**Comment by mtheall** [comment]
We just mean change the names while you're changing the related code anyway.

**Comment by LunarCookies** [comment]
Yes I know, but the rest of the functions use the same nomenclature when naming variables. That's why I  am reticent about changing them.

**Comment by WinterMute** [comment]
Awesome, cheers.

**Pull request merged**
