### PR TITLE
Define SVC functions as inlined functions

### PR DESCRIPTION
**Pull request by 173210**
This commit reduces overheads to call SVC functions.
This trick is used also on Linux kernel. I hope my commit will be utilized for implementing other SVCs.

### CODE REVIEW

**Comment by fincs** [comment]
No, this is extremely brittle and it is guaranteed to produce problems with the compiler.

**Comment by profi200** [comment]
It's also not good pratice to place code in headers.

**Comment by fincs** [comment]
Err, placing code in headers is necessary in order for inlined functions to work.

**Comment by profi200** [comment]
Not really. You can still just place the prototype in the header and the code in another file. The compiler will accept both ways.

**Comment by 173210** [comment]
It highly depends on GCC. It may not work on another compilers. But it won't be a problem because it had already had asm and attributes statements which depends on GCC.
To see how it depends on GCC, compile with -pedantic option.
To see output code, disassemble with objdump.

**Comment by 173210** [comment]
fincs, you may worry about optimization, but you don't have to.
asm statements which I wrote includes information to optimize code properly.
In the detail, all asm statement has information about registers which are used to input arguments/ouput results/call SVC.

**Comment by WinterMute** [comment]
@173210 asm is a gnu extension which will cause errors with -ansi and various -std options. It would be better to use __asm__ for these. Is adding lr to the clobber list really necessary? I was under the impression that these calls couldn't be used from supervisor mode.

Did you do any checks to see what registers other than input & output are changed, if any?

@profi200 it's not good practice to place non inlined code in headers, static inline code is perfectly acceptable. I'm also reasonably sure that you have to enable link time optimisation to get code in separate translation units to inline.

**Comment by 173210** [comment]
I think we should use __asm__ for header files, but I used asm because asm is already used. I think we should fix them with another commit.
Well, actually LR is not necessary. I'll fix them.

**Comment by 173210** [comment]
I'll close this commit because WinterMute found a problem.

**Pull request closed without merging**
