### PR TITLE
Added CirclePad example

### PR DESCRIPTION
**Pull request by Aurelio92**
This example shows how to get Circle Pad position and prints them on
the top screen

### CODE REVIEW

**Comment by WinterMute** [comment]
Could you combine this with the pad example and update for latest libctru/devkitARM please?

It's basically just a matter of switching -mfloat-abi=softfp to -mfloat-abi=hard, changing gfxInit to gfxInitDefault and removing the rest of the init/exit functions.

Cheers

**Comment by Aurelio92** [comment]
Yeah, sure! I'll do it right now :)

2015-02-18 16:13 GMT+01:00 Dave Murphy <notifications@github.com>:

**Comment by Aurelio92** [comment]
@WinterMute I did the updates you asked. Is it ok now? :)

**Comment by WinterMute** [comment]
looks good, might rename it though

**Comment by Aurelio92** [comment]
Yeah, I thought about it, but I didn't know how to rename it. If you have
an idea on how to rename it, feel free to do it :D

2015-02-18 18:50 GMT+01:00 Dave Murphy <notifications@github.com>:

**Comment by WinterMute** [comment]
git mv <oldname> <newname>

I have no idea if that works for pull requests on here though

**Comment by Aurelio92** [comment]
No wait, I meant that I don't know with which name I should rename it :D

2015-02-18 19:16 GMT+01:00 Dave Murphy <notifications@github.com>:

**Pull request merged**
