### PR TITLE
FRD update

### PR DESCRIPTION
**Pull request by Ryuzaki-MrL**
Added FRD_GetFriendMii. Also fixed MiiData structure padding + other stuff.

### CODE REVIEW

**Comment by Ryuzaki-MrL** [comment]
Just noticed the other pull request also implements this function. Should I remove it from this one?

**Comment by fincs** [comment]
Yes please. Could you rebase on top of latest master, which now has the formatting fixes? (not sure if it has the MiiData padding fixed)

**Comment by Ryuzaki-MrL** [comment]
Closing due to failed travis CI check.

**Comment by fincs** [comment]
It's not your fault, it's Travis' fault. Ignore it.

**Comment by fincs** [comment]
There we go, Travis fixed itself.

**Comment by joel16** [comment]
Could you revert this? Testing this with FriendMii, seems to have broken some things which were working fine with the previous commit to FRD. 

"IsIncludedInFriendList" showing up false for every friend.
It also doesn't get your first friend's favourite game titleID correctly.
The only thing it seems to be doing right is the pragma pop and push used for the MiiData struct.

**Comment by Ryuzaki-MrL** [comment]
Try changing 0x1 back into 0xFF for IsIncludedInFriendList, and passing "count" as "offset" for GetFriendFavoriteGame. These might be the breaking changes.

**Comment by fincs** [comment]
Friendly reminder that you're supposed to use stable libctru releases when possible. A followup PR that fixes the issue is welcome.

**Comment by joel16** [comment]
@fincs I'm aware of that but when you are one of the contributors to the said service, you can't help but test to make sure things are still working as is. Anyways on-topic: I'll submit a PR once I get home and test my changes.

**Pull request merged**
